### ISSUE TITLE
Implement auto removing package after init command completion

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-project-initializator#3]
We need to add the last step of the `init` command which will ask "Do you want to uninstall project-initializator package?" with the default `yes` answer.

On the `yes` answer package should be uninstalled via composer

**Comment by pirs1337** [comment]
> @pirs1337 could you please change command to skip this promt?
> 
> <img alt="image" width="1153" src="https://private-user-images.githubusercontent.com/9486872/389606259-67967231-e1f0-42c9-a71b-81ec5f8ee246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTcyNTEsIm5iZiI6MTczMzExNjk1MSwicGF0aCI6Ii85NDg2ODcyLzM4OTYwNjI1OS02Nzk2NzIzMS1lMWYwLTQyYzktYTcxYi04MWVjNWY4ZWUyNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDJUMDUyMjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJjZjMzOTg5OGJkNzZlNzBkMTQyNWRlMTBkNmVjZmJjNGQwNzE0NWE5MDkxNjhjN2YzYzg2MGE5MDFiMzI0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1-Q8ntQRysPQ2KVj_jNRfsSlHY9LdB4VFoOUzv-NN-A">

fixed

**Comment by DenTray** [comment]
@pirs1337 looks great! thanks!
