### ISSUE TITLE
Add new init command step

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-project-initializator#4]
We need to extend the `init` command to install basic RonasIT packages:
- LaravelHelpers
- LaravelEntityGenerator
- LaravelSwagger
- [LaravelMedia](https://github.com/RonasIT/laravel-media) (optionally via question)

**Comment by DenTray** [comment]
@pirs1337 all good, but let's make some improvements:

1. Let's remove "testing" keyword from the swagger package to prevent this prompt

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/e32080e7-c368-45e4-ada2-0e6c5ede569c">

2. Let's add some colored output about installation process like:
- "Installing $package..."
- "Package $package has been successfully installed!"

**Comment by pirs1337** [comment]
done

**Comment by DenTray** [comment]
@pirs1337 thanks!
